# Default settings shared by all environments
default: &default
  adapter: postgresql       # Use PostgreSQL as the database adapter
  encoding: unicode         # Set the character encoding to Unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  # Set the max number of connections in the pool
  timeout: 5000             # Set the timeout for database connections
  url: <%= ENV['DATABASE_URL'] %> # Use the DATABASE_URL environment variable for database connections

# Development environment settings
development:
  <<: *default              # Inherit settings from the "default" block
  database: awakencms_development  # Name of the development database

# Test environment settings
test:
  <<: *default              # Inherit settings from the "default" block
  database: awakencms_test   # Name of the test database

# Production environment settings
production:
  <<: *default              # Inherit settings from the "default" block
  database: your_app_name_production  # Name of the production database
  username: <%= ENV['DB_USERNAME'] %> # Use an environment variable for the database username
  password: <%= ENV['DB_PASSWORD'] %> # Use an environment variable for the database password
  host: <%= ENV['DB_HOST'] %>         # Use an environment variable for the database host
  port: <%= ENV['DB_PORT'] %>         # Use an environment variable for the database port
